name: Continuos Integration
on: [push]
jobs:
  Check-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.x
          architecture: x64

      - name: Install Requirements
        run: make install-dev

      - name: Lint Code
        run: make flake8

  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.x
          architecture: x64

      - name: Install Requirements
        run: make install-dev

      - name: Run Unit Tests
        run: make test

  Create-Test-Docker-Image:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: [Check-Lint, Run-Tests]
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/double_check:test
